export const PRESETS = [
  {id:'bb144', name:'Bivariate bicycle · [[144, 12, 12]]', dimension:2, ideal:'x^12 - 1, y^6 - 1', polynomials:['x^3 + y + y^2','y^3 + x + x^2'], note:'The 144-qubit bivariate bicycle code. Two qubit blocks and one translation family of each check type.', reference:'https://arxiv.org/abs/2308.07915', source:'Bravyi et al. · Bivariate bicycle codes'},
  {id:'tt72', name:'Trivariate tricycle · 72 qubits', dimension:3, ideal:'x^4 - 1, y^3 - 1, z^2 - 1', polynomials:['1 + y + x*y^2','1 + y*z + x^2*y^2','1 + x*y^2*z + x^2*y'], note:'A 72-qubit tricycle code with three qubit blocks. The middle degree q = 1 gives one X family and three Z families.', reference:'https://arxiv.org/abs/2601.18879', source:'MM manuscript · Trivariate tricycle example'},
  {id:'mm486', name:'Multivariate multicycle · [[486, 24, 12]]', dimension:4, ideal:'x^3 - 1, y^3 - 1, z^3 - 1, w^3 - 1', polynomials:['1 + x*y + y^2*z','1 + y*z + z^2*w','1 + z*w + x*w^2','1 + x*w + x^2*y'], note:'A four-polynomial MM code with six qubit blocks and four families of each check type. Each representative has weight 9.', reference:'https://arxiv.org/abs/2601.18879', source:'MM manuscript · 486-qubit example'},
  {id:'mm648', name:'Multivariate multicycle · [[648, 60, 9]]', dimension:4, ideal:'x^3 - 1, y^3 - 1, z^3 - 1, w^4 - 1', polynomials:['(1 + y)*(1 + z*w)','(1 + z)*(1 + w*x)','(1 + w)*(1 + x*y)','(1 + x)*(1 + y*z)'], note:'A factored-polynomial MM code on a 3 × 3 × 3 × 4 lattice. The w axis appears as four consecutive 3D slices.', reference:'https://arxiv.org/abs/2601.18879', source:'MM manuscript · 648-qubit worked example'},
  {id:'toric4', name:'4D toric · [[96, 6, 4]]', dimension:4, ideal:'x^2 - 1, y^2 - 1, z^2 - 1, w^2 - 1', polynomials:['1 + x','1 + y','1 + z','1 + w'], note:'The 4D toric code: one binomial per axis. The six blocks correspond to the six types of coordinate planes.', reference:'https://arxiv.org/abs/2601.18879', source:'MM manuscript · Toric subfamily'},
  {id:'haah', name:'Haah’s cubic code · 128 qubits', dimension:3, ideal:'x^4 - 1, y^4 - 1, z^4 - 1', polynomials:['1 + x + y + z','1 + x*y + x*z + y*z'], note:'Two polynomial generators on a cubic lattice. Its two qubit blocks emphasize that lattice dimension and polynomial count are independent.', reference:'https://arxiv.org/abs/1101.1962', source:'Haah · Local stabilizer codes in three dimensions'},
  {id:'toric2', name:'2D toric · [[50, 2, 5]]', dimension:2, ideal:'x^5 - 1, y^5 - 1', polynomials:['1 + x','1 + y'], note:'A simple starting point: two qubits per lattice site and weight-4 X and Z checks.', reference:'https://arxiv.org/abs/quant-ph/9707021', source:'Kitaev · Toric code'}
];
